# Generated by Django 2.1.7 on 2019-03-18 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import restaurant_app.models.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_first_name', models.CharField(blank=True, default='', max_length=100)),
                ('_last_name', models.CharField(blank=True, default='', max_length=100)),
                ('_email', models.EmailField(max_length=100)),
                ('_email_confirmed', models.BooleanField(default=False)),
                ('_password', models.CharField(max_length=100)),
                ('_birthday', models.DateField(blank=True, default=None, null=True)),
                ('_gender', models.IntegerField(choices=[(1, restaurant_app.models.enums.PersonGender(1)), (2, restaurant_app.models.enums.PersonGender(2)), (3, restaurant_app.models.enums.PersonGender(3)), (4, restaurant_app.models.enums.PersonGender(4))])),
                ('_group_of_age', models.IntegerField(choices=[(1, restaurant_app.models.enums.GroupOfAge(1)), (2, restaurant_app.models.enums.GroupOfAge(2)), (3, restaurant_app.models.enums.GroupOfAge(3)), (4, restaurant_app.models.enums.GroupOfAge(4)), (5, restaurant_app.models.enums.GroupOfAge(5)), (6, restaurant_app.models.enums.GroupOfAge(6)), (7, restaurant_app.models.enums.GroupOfAge(7))])),
                ('_auth_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
