# Generated by Django 2.1.7 on 2019-03-18 22:50

from django.db import migrations, models
import django.db.models.deletion
import restaurant_app.models.enums


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(blank=True, default='', max_length=100)),
                ('_description', models.CharField(max_length=250)),
                ('_phone', models.CharField(blank=True, default='', max_length=20)),
                ('_type', models.IntegerField(choices=[(1, restaurant_app.models.enums.RestaurantType(1)), (2, restaurant_app.models.enums.RestaurantType(2)), (3, restaurant_app.models.enums.RestaurantType(3)), (4, restaurant_app.models.enums.RestaurantType(4)), (5, restaurant_app.models.enums.RestaurantType(5))])),
                ('_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.Person')),
            ],
        ),
    ]
