# Generated by Django 2.1.7 on 2019-03-18 23:40

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('restaurant_app', '0002_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='_media',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_media', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
