# Generated by Django 2.1.7 on 2019-03-18 23:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('restaurant_app', '0003_restaurant__media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_title', models.CharField(blank=True, default='', max_length=100)),
                ('_description', models.CharField(max_length=250)),
                ('_date', models.DateField(blank=True, null=True)),
                ('_appetizer', models.CharField(max_length=100)),
                ('_main_course', models.CharField(max_length=100)),
                ('_dessert', models.CharField(max_length=100)),
                ('_drink', models.CharField(max_length=100)),
                ('_total_votes', models.IntegerField(blank=True, default=0, null=True)),
                ('_media', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_media', to=settings.FILER_IMAGE_MODEL)),
                ('_restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.Restaurant')),
                ('_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.Person')),
            ],
        ),
    ]
