# Generated by Django 2.1.7 on 2019-03-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0004_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_created_date', models.DateField(auto_now_add=True)),
                ('_menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.Menu')),
                ('_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant_app.Person')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('_user', '_menu')},
        ),
    ]
